<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.9 setup script
 * Date: Tue, 17 Jan 2012 14:16:59 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: rtf [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'rtf';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'phil';
$cfg['Servers'][$i]['password'] = '************';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ZipDump'] = false;
?>